### ISSUE TITLE
don't find pom.xml in most projects

### ISSUE THREAD

**Issue by frank-dkvan** [KnowageLabs/Knowage-Server#1]
don't find pom.xml in most projects...

**Comment by davide-zerbetto** [comment]
@frank-dkvan Knowage Server project will be mavenized in next months

**Comment by frank-dkvan** [comment]
got it. see if I can contribute something there :-)

**Comment by davide-zerbetto** [comment]
thank you! it would be very nice if you can contribute! I think it should be better if we coordinate between each other, but please wait a little bit, we need to design this mavenization process. I'll come back to you with more details and I'll ask you how you can contribute, is this fine with you? Remember that you will also subscribe the [Knowage Contributor License Agreement](https://www.clahub.com/agreements/KnowageLabs/Knowage-Server) for contributing to the Knowage project

**Comment by frank-dkvan** [comment]
okay :-)

**Comment by frank-dkvan** [comment]
by the way, I may contribute to chinese localization as well. as you may know, china market has large population and about 1 billion internet users. there would be a very strong potential needs there. let me know if needed :-)

**Comment by aportosa** [comment]
Hello frank-dkvan,
first of all, I'm glad to hear that you are willing to contribute on Knowage localization.

I can let you know in advance that we are setting up out translation tool based on Zanata (http://zanata.org/), which will be ready-to-go in a couple of week.

Your contribution will be really appreciated! :+1:

Thus, I would suggest you to be patient for a couple of week and then start to contribute directly with our translation tool. When ready, it will be publicly announced on our website!

**Comment by frank-dkvan** [comment]
still don't find pom.xml in most projects of the updated source code release...how to import these projects into Eclipse? cld u pls provide a tutorial?  I simply import these projects into Eclipse, but it does NOT work. my Eclipse version is Neon Release Candidate 1 (4.6.0RC1)

**Comment by frank-dkvan** [comment]
would you please provide a quick guide about how to import these projects into Eclipse correctly?  by the way, what IDE do you recommend, Eclipse, InteliJ,or anything else?

**Comment by aportosa** [comment]
Hi frank-dkvan,
we are happy to announce that we finally set up Zanata for Knowage.
You can find it at: https://www.knowage-suite.com/zanata/
The account is the same of the portal where I guess you are already registered in.
If you don't know Zanata, please have a look at the docs before start.

Moreover, please report bugs by using our issue tracker: https://www.knowage-suite.com/jira
If you have any technical question, you can instead use out Q&A: https://www.knowage-suite.com/qa

Issue via Github will be disable soon.
