### ISSUE TITLE
(Knowage 7.0.0 RC) Error in Cockpit Selector Widget : date range not found

### ISSUE THREAD

**Issue by sonim76** [KnowageLabs/Knowage-Server#103]
**Describe the bug**
Add on Cockpit "Selector Widget", select the dataset and then date field, knowage show me two choice:
- single date; 
- range dates.

But if I check single or range dates and then save, widget show me only list of checkboxs or radiobuttons about date field selected. 
Knowage Not showing datepicker for date fields selected.

**To Reproduce**
1. Go to 'Cockpit Document' (edit mode)
2. Click on 'Add Widget'
3. Click on 'Selector'
4. Set the 'Dataset' and select date field 
5. Knowage show two icons (single or range datepickers images)
6. Click on 'Range date icon'
7. Click on Save button
8. Widget created show list of dates (checkbox)

**Expected behavior**
I expect to use datepicker

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 72.0.3626.121

![datepicker](https://user-images.githubusercontent.com/54672898/63944270-8734a400-ca71-11e9-9a29-044e2e994098.PNG)

**Comment by Shinar125** [comment]
Hi. 
Are you solved this issue?
