### ISSUE TITLE
how to setup  source code build and run

### ISSUE THREAD

**Issue by devendra1988** [KnowageLabs/Knowage-Server#104]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devendra1988** [comment]
how to setup  source code build and run

**Comment by Redjaw** [comment]
For every information regarding Knowage build, installation and functionalities please read the official documentation:
https://knowage-suite.readthedocs.io/
