### ISSUE TITLE
Cannot configure cache: Data source for writing is not defined

### ISSUE THREAD

**Issue by wilsonflores** [KnowageLabs/Knowage-Server#115]
I'm trying to figure out what can be wrong with my resources configurations in the server.xml file. I've declared all the resources and its databases but I'm still getting this error:
**Cannot initialize cache java.lang.Exception: Cannot configure cache: Data source for writing is not defined. Please select one in the data sources definition panel.** This same error appears in the executable version but the database knowage_demo (mariadb) has the roles, menus and etc.

And then I have an error while loading user by idbiadmin:
**An unexpected error occurred while initializieng default users it.eng.spagobi.commons.dao.SpagoBIDAOException: Error while loading user by idbiadmin**

![knowage-server](https://i.ibb.co/gM8JmGk/knowage-server.jpg)

**Comment by n3ils** [comment]
Hi @wilsonflores,

to complete cache configuration, datasource must be enable for cache usage. To do this, go to Data sources menu --> Select data source for cache and make sure that Read Only is set to "Read and write" and "Use as cache" check is selected. (_See figure below_)

![Cache_datasource](https://user-images.githubusercontent.com/53894250/81042760-1ae82b00-8eb1-11ea-9cb1-adbdcc4a5848.PNG)

The second error is related to a problem during loading user "_biadmin_" . Can you please give me the full log so I can investigate?

Moreover, I also ask you for some information:
1. which version of Knowage are you using?
2. is it a Community or an Enterprise Edition?
3. which database are you using?

Thank you

Regards
Alberto

**Comment by Redjaw** [comment]
Fixed in [issues-162](https://github.com/KnowageLabs/Knowage-Server/issues/162)
