### ISSUE TITLE
#Bug: Parameters are not appending to the URL while creating the data-set using REST API

### ISSUE THREAD

**Issue by VivekKumar856** [KnowageLabs/Knowage-Server#116]
I was trying to Create the DataSet using the REST API with the "GET" method and "Parameters", but "Parameters" was not appending to the URL.

There should be two fixes can be done for resolving the above issue:

1. "getQuery()" method should be changed in RESTDataProxy.java file-
protected List<NameValuePair> getQuery() {
		List<NameValuePair> res = new ArrayList<NameValuePair>(); // ArrayList size should not be fixed to 3
		if (offsetParam != null) {
			if (offset != OFFSET_NOT_DEFINED) {
				res.add(new NameValuePair(offsetParam, Integer.toString(offset)));
			}
			Assert.assertTrue(fetchSizeParam != null, "fetchSizeParam!=null");
			if (fetchSize != FETCH_SIZE_NOT_DEFINED) {
				res.add(new NameValuePair(fetchSizeParam, Integer.toString(fetchSize)));
			}
		}

		if (maxResultsParam != null && maxResults != MAX_RESULT_NOT_DEFINED) {
			res.add(new NameValuePair(maxResultsParam, Integer.toString(maxResults)));
		} else {
			if (ngsi) {
				res.add(new NameValuePair("limit", NGSI_LIMIT));
			}
		}
		
		//Added new code for appending the Parameters to the URL
		if(this.parameters != null & this.parameters.size() > 0) {
			Iterator keys = this.parameters.keySet().iterator();
			while (keys.hasNext()) {
				String key = (String) keys.next();
				Object val = this.parameters.get(key);
				if (val instanceof String) {
					if (val != null && !val.equals("") && !val.equals("''")) {
						String curval = (String)val;
						curval = curval.replaceAll("'", "");
						res.add(new NameValuePair(key, curval));
					}
				}
			}		
		}
		//END
		return res;
	}

2. In "makeRequest()" method In RestUtilities.java file passing "null" in place of "queryParams"

public static Response makeRequest(HttpMethod httpMethod, String address, Map<String, String> requestHeaders, String requestBody,
			List<NameValuePair> queryParams) throws HttpException, IOException, HMACSecurityException {
		return makeRequest(httpMethod, address, requestHeaders, requestBody, queryParams, false);
	}

**Comment by marcob1995** [comment]
Hi @VivekKumar856,
thank you for your contribution!
We applied the changes you proposed. Let us know if you encounter other issues.
