### ISSUE TITLE
BIRT Report Mobile Responsive Issue

### ISSUE THREAD

**Issue by harikrishnan891** [KnowageLabs/Knowage-Server#117]
Reports created on BIRT , and deployed in knowage and Integrate it in our Angular Project , The mobile view is not responsive , as it is always open a pdf format on mobile view , So Crossnavigation does not work.Cockpit Documents are Good in Mobile view

**Comment by Redjaw** [comment]
Hi,
if your priority is the mobile support remember that BIRT is table based, so create something responsive with it will be very difficult and tricky.
For that motivation, on small devices the view of BIRT report was very difficult to made usable, so we decided to make them available as zoomable and navigable pdf.
If you are interested in continuity between cross-navigation on mobile please create report using the cockpit, which has fluid mobile support on lanscape orientation.
