### ISSUE TITLE
Pass parameters / Add driver to document

### ISSUE THREAD

**Issue by rlagarde** [KnowageLabs/Knowage-Server#120]
**Describe the bug**
I want to give a parameter value when calling getDocumentUrl in sdk.
I manage to call the correct document with the desired role but parameters isn't read at all. 
No error is thrown.
Probably related: 
I cannot add a driver to a document (cockpit) 
I get an ok message in knowage interface but error is logged.
then the document won't execute anymore.
Also the driver cannot be removed from document details panel. 

**To Reproduce**
1. create datasource
2. create a dataset with parameter 
3. create analytical driver
4. create document 
5. edit document details ([error in logs](https://pastebin.com/GGzdpRKB))
6. add driver to document ([no error in knowage](https://snipboard.io/h5rtiF.jpg) but [new error in logs](https://pastebin.com/uKVVqMBP))
7. launch document and get the error  ([error in knowage](https://snipboard.io/qHnwFN.jpg) interface and [logs](https://pastebin.com/Khe1ywt6))

**Expected behavior**
Launch document and set the driver in the datasource config panel

**Screenshots**
![image](https://user-images.githubusercontent.com/24719323/74160337-88bbe800-4c1d-11ea-8f3f-f23690d0dad4.png)
^ seems ok but not v
![image](https://user-images.githubusercontent.com/24719323/74160227-60cc8480-4c1d-11ea-9fc9-cd044f6f43ba.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: firefox / chrome
 - Version 7.1 / postgresql databases

**Comment by n3ils** [comment]
Hi @rlagarde ,

We did some checks in our test environment but, unfortunately, we didn't reproduce the error.

Can you give me the log files so I can better analyze the problem?

Also, can you tell me what the full version of Knowage is (you can see it from the main menu by clicking on "Information")?

Thank you

Alberto

**Comment by rlagarde** [comment]
Hi @n3ils ,
thanks for answering.
The logs are linked in OP. I was using knowage 7.1.0
Installing 7.1.3 fixed this issue for me.
thanks
