### ISSUE TITLE
Error in document details page

### ISSUE THREAD

**Issue by rlagarde** [KnowageLabs/Knowage-Server#121]
Hi, 

**Bug**
Open the document details page throw error (fresh default installation: 7.1 CE installer)

**To Reproduce**
1. fresh install using embeded mariadb server,
2. login using biadmin
3. create a folder in functionnalities tree : demo_folder
4. give admin all authorizations in roles management.
5. create a cockpit document in document browser/demo_folder
6. save cockpit document
7. back to document browser 
8. click the eye icon then Edit Document (pencil)
9. get error in browser console and knowedge log

**Screenshots**
![image](https://user-images.githubusercontent.com/24719323/74648140-5e1de200-517d-11ea-9406-855bdf8027ab.png)
![image](https://user-images.githubusercontent.com/24719323/74648196-7c83dd80-517d-11ea-8923-2de8f8d83b96.png)

**Desktop:**
 - OS: windows 10
 - Browser: chrome, firefox, edge
 - Version: knowage CE 7.1 embedded mariadb server

**Comment by rselakovic** [comment]
This issue is fixed on new version of Knowage 7.2 that will be released probably next month

**Comment by rlagarde** [comment]
This has been fixed in 7.1.7
Thanks
