### ISSUE TITLE
Does not work with MySQL > 5.5

### ISSUE THREAD

**Issue by Glagnar** [KnowageLabs/Knowage-Server#14]
The guide states the MySQL version should be: MySQL Server 5.5 or above already installed.
https://www.knowage-suite.com/site/wp-content/uploads/2018/03/Knowage-CE-Installer-Getting-started_6_1_1.pdf

But it does not work with MySQL8

**Comment by Glagnar** [comment]
It does not work with 5.7 either. Please fix this, or update the documentation.

**Comment by aportosa** [comment]
Knowage has been tested against MySQL 5.7. Please use the correct JDBC driver, and it will work.
