### ISSUE TITLE
parameterized REST request is not working

### ISSUE THREAD

**Issue by JeffJochems** [KnowageLabs/Knowage-Server#142]
**Issue**
When contructing a REST dataset, I would like to use a paramter in my request body.
According to the documentation, this is possible with the standard syntax `$P{parameter_name}`. When doing so however, knowage does not respond as expected. 
It either produces an error when the (number) parameter is passed literaly in this way e.g. `{"year":$P{year}}`: 400 Bad request
Or, when the parameter is passed as a string, it results in knowage sending a request with $P{parameter_name} directly to the API. E.g. when sending `{"year":"$P{year}"}`, my API recieves `{"year":"$P{year}"}`.

**How to reproduce**
To reproduce this, let's use the publicly available API: [dummy.restapiexample.com](http://dummy.restapiexample.com/)
1. Create a knowage dataset with a non paramterized request body for the example API [screenshots 1,2]
2. The preview results in the correct API response [screenshot 3]
3. Set the paramter in Knowage and parameterize the request body with "$P{paramter_name}" [screenshot 4,5]
4. See the hardcoded string sent to the API with preview [screenshot 6]

**Expected behavior**
When using a parameter in the request body it should result in the same response as when these parameters are specified explicitly. (Screenshot 6 should be the same as screenshot 3)

**Screenshots**
Screenshot 1 and 2:
![ex_1](https://user-images.githubusercontent.com/9891342/90402948-817c0800-e0a0-11ea-8a47-a4777739be7a.PNG)
![ex_2](https://user-images.githubusercontent.com/9891342/90402955-85a82580-e0a0-11ea-83b6-9f6ee0670137.PNG)

Screenshot 3:
![ex_3](https://user-images.githubusercontent.com/9891342/90402970-8b057000-e0a0-11ea-99be-f34bbaa8fbea.PNG)

Screenshot 4 and 5:
![ex_4](https://user-images.githubusercontent.com/9891342/90402978-8f318d80-e0a0-11ea-8e6c-65143b278086.PNG)
![ex_5](https://user-images.githubusercontent.com/9891342/90402995-9789c880-e0a0-11ea-9b9f-3f55b142f63d.PNG)

Screenshot 6:
![ex_6](https://user-images.githubusercontent.com/9891342/90403030-a1133080-e0a0-11ea-9ca7-184e5bbbd040.PNG)

The error i recieve when trying to post a numerical parameter is:
![ex_7](https://user-images.githubusercontent.com/9891342/90403293-0bc46c00-e0a1-11ea-8738-31fb91e4b644.PNG)

**Comment by kerny3d** [comment]
Hi @JeffJochems, it's a known problem and I have an assigned issue about it in our internal tracker. Actually, i don't know when I will have time to schedule the fix, I hope to work on it before September.
