### ISSUE TITLE
Cannot compile project with maven

### ISSUE THREAD

**Issue by vladiricoemergya** [KnowageLabs/Knowage-Server#16]
I can't compile the project with maven. Return ERROR is:

[INFO] Reactor Summary:
[INFO] 
[INFO] knowage-ce-parent .................................. SUCCESS [  0.522 s]
[INFO] knowage-jdbc-core .................................. SUCCESS [  2.251 s]
[INFO] knowage-utils-json ................................. SUCCESS [  0.875 s]
[INFO] knowage-utils ...................................... SUCCESS [  6.559 s]
[INFO] qbe-core ........................................... SUCCESS [  2.391 s]
[INFO] spagobi-cwm ........................................ SUCCESS [  0.892 s]
[INFO] spagobi-commons-core ............................... SUCCESS [  6.772 s]
[INFO] spagobi-metamodel-core ............................. SUCCESS [  1.746 s]
[INFO] spagobi-metamodel-utils ............................ SUCCESS [  0.920 s]
[INFO] knowage-dao ........................................ FAILURE [  0.326 s]
[INFO] knowage-core ....................................... SKIPPED
[INFO] knowageoauth2securityprovider ...................... SKIPPED
[INFO] knowage ............................................ SKIPPED
[INFO] knowagejasperreportengine .......................... SKIPPED
[INFO] spagobi.birt.oda ................................... SKIPPED
[INFO] knowagebirtreportengine ............................ SKIPPED
[INFO] slimerjs-wrapper ................................... SKIPPED
[INFO] knowagecockpitengine ............................... SKIPPED
[INFO] knowagecommonjengine ............................... SKIPPED
[INFO] knowagedataminingengine ............................ SKIPPED
[INFO] knowagegeoreportengine ............................. SKIPPED
[INFO] knowagekpiengine ................................... SKIPPED
[INFO] knowagemeta ........................................ SKIPPED
[INFO] knowagenetworkengine ............................... SKIPPED
[INFO] knowageqbeengine ................................... SKIPPED
[INFO] knowagesvgviewerengine ............................. SKIPPED
[INFO] knowagetalendenginclientapi ........................ SKIPPED
[INFO] knowagetalendengine ................................ SKIPPED
[INFO] knowagewhatifengine ................................ SKIPPED
[INFO] knowagesdk ......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 29.239 s
[INFO] Finished at: 2018-06-11T14:45:24+00:00
[INFO] Final Memory: 53M/470M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project knowage-dao: Could not resolve dependencies for project it.eng.knowage:knowage-dao:jar:6.1.1-SNAPSHOT: Could not transfer artifact it.eng.knowage:knowage-utils:jar:tests:6.1.1-SNAPSHOT from/to jaspersoft (http://jaspersoft.artifactoryonline.com/jaspersoft/jr-ce-releases): Failed to transfer file: http://jaspersoft.artifactoryonline.com/jaspersoft/jr-ce-releases/it/eng/knowage/knowage-utils/6.1.1-SNAPSHOT/knowage-utils-6.1.1-SNAPSHOT-tests.jar. Return code is: 409 , ReasonPhrase:. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :knowage-dao

**Comment by aportosa** [comment]
How did you start the build? Please go in the knowage-ce-parent directory and execute mvn clean install. Afeter, you could also package again with Maven.
