### ISSUE TITLE
"unable to load data" error with REST data set

### ISSUE THREAD

**Issue by agaldemas** [KnowageLabs/Knowage-Server#165]
**Describe the bug**
using Knowage 7.3.0-S deployed with docker-compose.

any widget (table or map) on **REST data set** querying Orion Context Broker, give an error 
"Unable to load data from dataset <name>
Please check dataset & widget config"

**To Reproduce**
1. create REST data set to an Orion Context Broker, check it's OK with Preview, check metadata is OK
2. in a document, add the previous REST data set
3. add a widget (table or map), save it
4. See error "Unable to load data from dataset <name>
Please check dataset & widget config", and no data in the widget
we can see an error in the chrome debugger

**Expected behavior**
widgets should work correctly

**Screenshots**
<img width="1000" alt="Capture d’écran 2021-02-20 à 11 51 27" src="https://user-images.githubusercontent.com/20285859/108593334-50dc9a00-7373-11eb-9e9b-d16f04fae452.png">

**Desktop :**
 - OS: MacOS
 - Browser: chrome
 - Version 88

**Additional context**
the issue seems not browser dependant, since the same error raise with Safari and Firefox !
the problem is the same with docker image version knowage-server-docker:7.4.0-SNAPSHOT, or 7.2
therefore it seems to be something i miss in the configuration of the data set itself or in the document

**Comment by agaldemas** [comment]
Important to know : 
I managed to get data in the widget, after refreshing several times the document page with the button !

it iss clearly an issue in the web application, something like a timeout control... ???!!!

it's very embarrassing, since I need to make a demo next Wednesday February 24th... 

Please to provide a fix, as soon as possible, thanks in advance

**Comment by agaldemas** [comment]
Humm ! found the issue, it was a cache_ds configuration issue...
in docker image on dockerhub cache_ds is not properly configured....
Anyway this problem is not properly reported to the user, the error message is not enough, I had to have a look at the logs in the container to discover the reason of the error

**Comment by agaldemas** [comment]
May be it's a recommendation to add for an admin, to check the cache (cache_ds) data source is working !

**Comment by kerny3d** [comment]
Hi,

thank you for reporting it. We will try to update the documentation and we will update the docker-compose descriptors to add another DB for the cache.
