### ISSUE TITLE
Conection sql Server

### ISSUE THREAD

**Issue by jailtonurbano** [KnowageLabs/Knowage-Server#169]
I am using Knowage 7.2.18.

But my conection in mssql server dont run.
no log is generated

So. Windows Server 2012 r2

 thank.

Url:

jdbc:sqlserver://192.168.160.251;DatabaseName=DADOSADV;integratedSecurity=true

Driver
com.microsoft.sqlserver.jdbc.SQLServerDriver

Sql Server 2016

test button does nothing

**Comment by jailtonurbano** [comment]
com/microsoft/sqlserver/jdbc/SQLServerDriver has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**Comment by matmassa** [comment]
Dear jailtonurbano,
which version of Java are you using? I kindly suggest you to use Java 8 (it seems to be a Java version related issue).
Regards
Matteo

**Comment by Redjaw** [comment]
hi @jailtonurbano ,
did you manage to fix the issue changing the Java version?

**Comment by jailtonurbano** [comment]
Yes.
Run.

Em seg., 5 de jul. de 2021 às 05:57, Davide Vernassa <
***@***.***> escreveu:
