### ISSUE TITLE
The pie chart does not show the proportion outside the graph. What is the reason

### ISSUE THREAD

**Issue by Hello-Linux** [KnowageLabs/Knowage-Server#171]
the knowage version is 7.2.18 and 6.4.5 but my pie chart does not show the proportion outside the graph. What is the reason?
the official is
![微信图片_20210311180151](https://user-images.githubusercontent.com/17851645/110770163-f5c40600-8293-11eb-8bad-c20f99a6fec8.png)
but my chart is
![微信图片_20210311180617](https://user-images.githubusercontent.com/17851645/110770624-7edb3d00-8294-11eb-8684-97136f39cd06.png)

**Comment by Hello-Linux** [comment]
@Redjaw  @jason-fox  @kerny3d  @rselakovic  ? Are you here?

**Comment by jason-fox** [comment]
@Hello-Linux - my contribution to this repo has been very limited, so I can't help here I'm afraid.

**Comment by marcob1995** [comment]
Hi,
try by using this configuration:

![chart_conf](https://user-images.githubusercontent.com/38689029/113988798-1ca03880-9850-11eb-8aee-c93e60089ffb.jpg)

Bye,
Marco
