### ISSUE TITLE
Zanata account creation and verfication problem

### ISSUE THREAD

**Issue by urbalazs** [KnowageLabs/Knowage-Server#177]
It is not possible to create and verify new Zanata account for translation, because the activation email couldn't be received.

If I try to change the email, I got this error:

```
Proxy Error

The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request POST /zanata/account/inactive.

Reason: Error reading from remote server
```

I guess this is the problem for verification email sending, too. Can you please check the service?

**Comment by davide-zerbetto** [comment]
Thanks @urbalazs for the notice, we are working on it.

**Comment by davide-zerbetto** [comment]
Dear @urbalazs Zanata email issue should be solved. Could you please tell me if you are able to login into Zanata?

**Comment by urbalazs** [comment]
@davide-zerbetto I am now able to login into Zanata. In the meanwhile I translated the whole software offline into Hungarian. Now I have the Hungarian translations in both `.properties` and `.po` formats. What is better for you?

1. Add Hungarian language to Zanata in order to upload the translations. As I see, I cannot add new language.
2. Create a pull request with the .properties files.

**Comment by urbalazs** [comment]
Hi @Redjaw 
You asked me to use Zanata for further translations instead of creating pull request. Unfortunately, Zanata is not an option for me if it doesn't support the uploading of .po files because I have a well-proven offline translation workflow. [Based on its documentation](https://docs.zanata.org/en/release/user-guide/documents/upload-documents/#uploading-translation-documents) there should be an upload possibility, but I couldn't find it. Is it disabled?

I would like to backport my translation to version 6.4 but I didn't find the way for this.

**Comment by Redjaw** [comment]
Hi @urbalazs.
I know but just one file type for project can be selected on Zanata, and we have set the .properties.
I can backport your translations to 6.4 with the Zanata functionalities. I just need to take a check before.

**Comment by urbalazs** [comment]
@Redjaw is it possible to upload .properties files to Zanata? If so, I would be happy, because I can convert my translations form .po to .properties, so I can still use my well-proven offline translation workflow.

**Comment by Redjaw** [comment]
Hi,
at the moment the 6.4 version is no longer updated, so I suggest you to use the 7.4.
However if you really need that version please make a pull request for that branch and we will upload your files on Zanata like we did last time.
regards
