### ISSUE TITLE
Non-functioning SQL query on MSSQL

### ISSUE THREAD

**Issue by DavideDaSerra** [KnowageLabs/Knowage-Server#18]
If I disable cache than I select (one or more) values in a cockpit, the database returns this error:

> jdbc.SQLServerException: An expression of non-boolean type specified in a context where a condition is expected, near ','

. 

The error is due to MSSQL not accepting IN statements in WHERE clause. 
This is the query I got from the losgs when doing a selection.
```
select "ATC_1" AS "ATC_1", SUM("Importo_Scarto") AS "Importo_Scarto", SUM("Q_Scarto") AS "Q_Scarto" 
from (SELECT [ATC_1] ,[MESE] ,[ANNO] ,[Q_Scarto] ,[Importo_Scarto] FROM [dbo].[MyTable]) T 
where (("ANNO","MESE") IN ('2017','10'),('2018','03') 
and ("Invio") IN ('3') ) 
group by "ATC_1"
```

By now, a workaroung is to work with cache enabled, so this syntax is handled by MySQL and not by SQL-Server
#

**Comment by aportosa** [comment]
Thanks to have this reported. You can find binaries of Knowage 6.2.0-RC only, where MSSQL support has been enhanced.
