### ISSUE TITLE
MapWidget - Zoom on layer features extent

### ISSUE THREAD

**Issue by rlagarde** [KnowageLabs/Knowage-Server#190]
MapWidget doesn't center/zoom on features extent.
This seems to work when using wkt as spatial attribute but not with geoJSON nor String coordinates.
https://www.knowage-suite.com/qa/6118

Problem is WKT isn't showing any features except for heatmap.
I know this is another issue, but WKT would be a great option if it worked with all visualization types.

**Comment by kerny3d** [comment]
Hi,

thank you for your report. We will investigate on it.

**Comment by kerny3d** [comment]
See:
Master -> https://github.com/KnowageLabs/Knowage-Server/commit/407a94b4673450ba1a125682a9d188e3dec8102a
8.0 -> https://github.com/KnowageLabs/Knowage-Server/commit/8d06ed0e1d9fefe971c5a6009487c93c0b724825
