### ISSUE TITLE
Brazilian Portuguese localization

### ISSUE THREAD

**Issue by WandreyRangon** [KnowageLabs/Knowage-Server#2]
Can I contribute with the localization to Brazilian Portuguese?

Please confirm that this guide is still valid:
http://wiki.spagobi.org/xwiki/bin/view/spagobi_server/Internazionalization

Thank you very much!

Brazil is a country with a population of more than 200 million, very rich and I am sure that Knowage solution will be very well received by the open source community
Fork created:
https://github.com/WandreyRangon/Knowage-Server

**Comment by aportosa** [comment]
Hello Wandrey,
first of all, I'm glad to hear that you are willing to contribute on Knowage localization.
**Please note the SpagoBI guide that you are referring to is not applicable to Knowage anymore.**
Also, there is not need to create a fork for this particular localization task.

I can let you know in advance that we are setting up out translation tool based on Zanata (http://zanata.org/), which will be ready-to-go in a couple of week.

Last but not least, you will probably be happy to know that about 40% of Knowage is already translated in Brazilian Portuguese! And you contribution will be really appreciated! :+1: 

Thus, I would suggest you to be patient for a couple of week and then start to contribute directly on out translation tool. When ready, it will be publicly announced on our website.

**Comment by WandreyRangon** [comment]
Thank you mr. Aportosa.
I am very happy to know that finally our language will be supported.
You guys did a great job with this new version, there are more than 4000 key/value pairs.
This eclipse plugin (https://marketplace.eclipse.org/content/resourcebundle-editor) helps a lot.
I believe using Zanata will give better configuration management.

The new features are highly anticipated and welcome.

I am very happy to be able to contribute with the localization to Brazilian Portuguese.

You guys are awesome!

**Comment by aportosa** [comment]
Hi WandreyRangon,
we are happy to announce that we finally set up Zanata for Knowage.
You can find it at: https://www.knowage-suite.com/zanata/

The account is the same of the portal where I guess you are already registered in.

If you don't know Zanata, please have a look at the docs before start.
