### ISSUE TITLE
Knowage 6.2 cockpit not working

### ISSUE THREAD

**Issue by DavideDaSerra** [KnowageLabs/Knowage-Server#20]
I tryed installing new version (ubuntu-server x86_64 18.04 LTS, java 1.8, mysql 5.7), but situation worsen: now the cockpit interface doesn't even start. (I installed)
But I can see that datasets beeing audited.

ADD: I get this error (and some other of same kind) in JS console:

`angular.js:1 Failed to load resource: net::ERR_CONNECTION_REFUSED`

this is the URL it looks for: `http://localhost:8080/knowage/js/lib/angular/angular_1.4/angular.js`

(it looks like it have localhost:8080 hardcoded somewhere) as I'm not running it on localhost but natted behind another port

If you need further information, just ask.

**Comment by anbernabei** [comment]
Hi you have to change HOST__URL cariable on server.xml

http://knowage-suite.readthedocs.io/en/latest/installation-guide/manual-installation.html#environment-variables-definition
Best Regrads
Angelo
