### ISSUE TITLE
Problem with UTF8

### ISSUE THREAD

**Issue by aportosa** [KnowageLabs/Knowage-Server#23]
<p>Wrong work with UTF8. In AdapterHTTP.handleMultipartForm replace</p>

<p>String value = item.getString();</p>

<p>on</p>

<p>String value = item.getString("UTF-8");</p>

<p> </p>

<p>You don't see defference in latin, but in cyrillic it's а big problem. </p>
<i>[KNOW-31] created by andrg</i>

**Comment by miniwark** [comment]
Maybe it is related to #15 with `-Dfile.encoding=UTF-8` who may need to be set in `CATALINA_OPTS` or `JAVA_OPTS` ?
