### ISSUE TITLE
Uploading CSV fails with [Fatal Error] :2:1: Content is not allowed in prolog

### ISSUE THREAD

**Issue by azbarcea** [KnowageLabs/Knowage-Server#293]
Trying to upload a csv file as a Data Set, fails with:
```
knowage-server-docker-knowage-1        | [Fatal Error] :2:1: Content is not allowed in prolog.
```

**To Reproduce**
1. Start knowledge-server using the `docker-compose`, based on `knowagelabs/knowage-server-docker:8.1.0-SNAPSHOT` image.
2. Login as `biadmin` or `biuser`
3. Go to `Data set`
4. Introduce the details on the `Details` tab, go to Type, select File, upload for example: https://landscape.cncf.io/data/items-export.json (was looking for a public .csv to be used for this bug, with which one can reproduce the issue)
5. Got the pop-up error:
```
Error
Impossible to parse file. Please, check its content and upload it again
```

Going to the logs:
```
knowage-server-docker-knowage-1        | [Fatal Error] :2:1: Content is not allowed in prolog.
knowage-server-docker-knowage-1        | [Fatal Error] :2:1: Content is not allowed in prolog.
```

**Expected behavior**
Expecting to proceed analyzing the data set using the BI tool. 

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: archlinux with docker `20.10.9, build c2ea9bc90b`
```
❯ git remote -v
origin  git@github.com:KnowageLabs/Knowage-Server-Docker.git
❯ git log -n 1
commit 4cace968e31df8f2fd9f90eadf581529ebb9d3c3 (HEAD -> master, origin/master, origin/HEAD)
Author: Marco Balestri <marco.balestri@eng.it>
Date:   Tue Nov 9 14:48:38 2021 +0100
```
 - Browser: Chromium
 - Version: `master` (i.e. `8.1.0-SNAPSHOT`)

**Smartphone (please complete the following information):**
NA

**Additional context**

**Comment by marcob1995** [comment]
Hello,
the link that you have attached points to a JSON file.
At the moment you can only upload CSV o XLS files.

Can you try again with a CSV file please? You can generate a random one at https://www.mockaroo.com/

Thanks,
Marco
