### ISSUE TITLE
Permission denied to run startup.sh after installation on MAC

### ISSUE THREAD

**Issue by frank-dkvan** [KnowageLabs/Knowage-Server#3]
the hint: -bash: ./startup.sh: Permission denied

**Comment by frank-dkvan** [comment]
by the way, why is the "All-in-One-Knowage" package (e.g. All-in-One-Knowage-6.0.0_RC_CE_20170429.zip) removed in the version 6.0 final release?  I think this is an easy way for new comers to demo and learn Knowage.  it's possible to make a new "All-in-One-Knowage" package for the version 6.0 final release?

**Comment by fralucch** [comment]
Hi, a new installer CE for Unix is available, now permissions are setted properly.
Sorry, a new "All-in-One-Knowage" is not planned for now...

**Comment by frank-dkvan** [comment]
yes, the Permission problem has been figured out in the updated release. but, I find it can only run in "root" environment?  is it possible to run in a non-root account?      and, the installer can not configure mySQL datasource. is it possible to configure other datasources, say, hsqldb, oracle, etc?

**Comment by aportosa** [comment]
Dear frank-dkvan,
please report bugs by using our issue tracker: https://www.knowage-suite.com/jira
If you have any technical question, you can instead use out Q&A: https://www.knowage-suite.com/qa

Issue via Github will be disable soon.
