### ISSUE TITLE
Arabic data are not showing in Cross Table widget

### ISSUE THREAD

**Issue by aportosa** [KnowageLabs/Knowage-Server#30]
<ol>
	<li>While adding the new Cross Table widget in Cockpit with the data that is available in a database table with Arabic Langauge then it is not showing the data in Arabic Characters. Although the Arabic characters are properly showing in normal Table widget.</li>
	<li>In Cross Table, if select the Date field in the row it is showing with time and there is no any setting where we can change it to show the only date instead of date and time.</li>
</ol>

<i>[KNOW-54] created by iftikharalam</i>

**Comment by miniwark** [comment]
Maybe it is related to #15 with `-Dfile.encoding=UTF-8` who may need to be set in `CATALINA_OPTS` or `JAVA_OPTS` ?
