### ISSUE TITLE
windows Knowage CE Installer problem

### ISSUE THREAD

**Issue by xihuishawpy** [KnowageLabs/Knowage-Server#305]
**Describe the bug**
window  start problem

**To Reproduce**
The installer is run as administrator.
1. double click D:\Knowage_data_platform\Knowage-Server-CE\bin\startup.bat
2. wrong log :
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

how to fix the problem?

thanks

**Comment by kerny3d** [comment]
Hi, this is not an applicative issue. We've fixed this problem already on the 8.0.x, it was just a missing dependency in our source code related to some third party libraries which are using slf4j.

**Comment by xihuishawpy** [comment]
> 

Thanks your reply.
now at windows env  , how to fix slf4j problem?

**Comment by kerny3d** [comment]
As I told you is not a problem but if you want to fix it you should download:

https://repo1.maven.org/maven2/org/slf4j/slf4j-log4j12/1.7.30/slf4j-log4j12-1.7.30.jar

and put it in "D:\Knowage_data_platform\Knowage-Server-CE\webapps\knowage-api\WEB-INF\lib" and "D:\Knowage_data_platform\Knowage-Server-CE\webapps\knowage-vue\WEB-INF\lib".

**Comment by xihuishawpy** [comment]
Thank you very much ~
