### ISSUE TITLE
Arabic data is not showing in Dashboard filter. Combo box is showing "??????"

### ISSUE THREAD

**Issue by aportosa** [KnowageLabs/Knowage-Server#32]
<p>Arabic data is not showing in Cockpit filter. The combo box is showing "??????".</p>
<i>[KNOW-56] created by iftikharalam</i>

**Comment by miniwark** [comment]
Maybe it is related to #15 with `-Dfile.encoding=UTF-8` who may need to be set in `CATALINA_OPTS` or `JAVA_OPTS` ?
