### ISSUE TITLE
Chart widget: wrong grouping of date time

### ISSUE THREAD

**Issue by aportosa** [KnowageLabs/Knowage-Server#36]
<p>Create a dataset with nearby datetimes as category and random values as measure.</p>

<p>Datetimes must have same date and increasing times by 10-seconds steps (e.g. '2018-02-08 10:27:10', '2018-02-08 10:27:20', '2018-02-08 10:27:30').</p>

<p>Create a line chart within a chart widget based on that dataset, setting datetimes on X axis and random values on Y axis.</p>

<p>Check that chart is displayed as expected.</p>

<p>Then in chart wizard enter "date time and grouping" settings, check "Enable datetime" and set date format equals to "Monday, Jan 1, 00:00:00".</p>

<p>Chart is not properly displayed anymore, because now all X coordinates are the same, making a straight vertical line.</p>
<i>[KNOW-66] created by fralucch</i>

**Comment by anbernabei** [comment]
Dear,
this problem is fixed on knowage 6.2
