### ISSUE TITLE
Hive Data Source

### ISSUE THREAD

**Issue by CamilloGioeELMI** [KnowageLabs/Knowage-Server#366]
Hive2 datasource doesn't work using Knowage8 on Windows 10 (I also checked Knowage8 using docker container)

1. Copy these files in [install_folder]\Knowage-Server-CE\lib folder
hadoop-common-2.7.3.2.6.4.0-91.jar
hive-common-1.2.1000.2.6.4.0-91.jar
hive-exec-1.21.2.2.6.4.0-91.jar
hive-jdbc-1.21.2.2.6.4.0-91.jar
hive-metastore-1.21.2.2.6.4.0-91.jar
hive-service-1.2.1000.2.6.4.0-91.jar
guava-annotations-r03.jar
guava-base-r03.jar
guava-primitives-r03.jar

2. Edit setenv.bat putting these line at the end
set "CLASSPATH=[install_folder]\Knowage-Server-CE\lib"

3. Create datasource using Apache Hive2 dialect. Test doesn't display informations if test connection is successfull. Then, save the datasource
![image](https://user-images.githubusercontent.com/66424835/151945906-08d14f4a-69d8-4828-80d5-73ae2746b8da.png)

4. Creata a dataset using Query and the data source created previously
5. Click on Preview
6. a "Method not supported" issue is displayed

This behavior is due to this class 
https://commons.apache.org/proper/commons-dbcp/jacoco/org.apache.commons.dbcp2/DelegatingConnection.java.html 
and in particular to isValid method
![image](https://user-images.githubusercontent.com/66424835/151946954-5b4f18ab-ca2c-4816-a3da-7697a0158732.png)

At the meantime, I applied a workaround editing just this class as follows
![image](https://user-images.githubusercontent.com/66424835/151947123-d0febd86-9754-47bb-9e82-cee456bb9b03.png)

Then, I had to copy the commons-dbcp2-2.9.0.jar file too

**Comment by matmassa** [comment]
Hi,
thank you for your suggestion. We are analyzing the code and we will work for an update for next releases.
Regards
Matteo
