### ISSUE TITLE
Lovs Managemt-Fixed list of values not support UTF-8 characters

### ISSUE THREAD

**Issue by aportosa** [KnowageLabs/Knowage-Server#38]
<p>First of all, I moved the demo database to the MySql Database, so far so good.</p>

<p>But when I trying to define a Lovs with UTF-8 characters, it seems like occur an encoding problem when previewing.</p>

<p>Please see the snapshot for details</p>
<i>[KNOW-68] created by funfan</i>

**Comment by miniwark** [comment]
Maybe it is related to #15 and `-Dfile.encoding=UTF-8` mays need to be set in `CATALINA_OPTS` or `JAVA_OPTS` ?
