### ISSUE TITLE
 can not create a new talent accounts in the new release. 

### ISSUE THREAD

**Issue by frank-dkvan** [KnowageLabs/Knowage-Server#4]
Knowage installer create a demo talent by default. but, I find the talent-configurate functionality in the old spagobi release (e.g. ver 5.2) has been removed in the new knowage release. how to create a new talent in the version 6?  otherwise, the community version is just a toy-version only for demo usage?

**Comment by aportosa** [comment]
Dear frank-dkvan,
please report bugs by using our issue tracker: https://www.knowage-suite.com/jira
If you have any technical question, you can instead use out Q&A: https://www.knowage-suite.com/qa

Issue via Github will be disable soon.

**Comment by miniwark** [comment]
Reopen ? Since Jira is not used anymore

**Comment by aportosa** [comment]
No need to reopen the issue.
The community edition does not have any facility to manage tenants, which is included in the enterprise edition. Read the [docs](https://knowage-suite.readthedocs.io/en/latest/administrator-guide/knowage-at-a-glance.html?highlight=tenant)

About Jira, old issues have been migrate here in Github, so no issue is lost.
