### ISSUE TITLE
ERR_CONNECTION_REFUSEd

### ISSUE THREAD

**Issue by aportosa** [KnowageLabs/Knowage-Server#41]
<p>I tryed to start the OLAP wizard template and I got the following error:</p>

<p><span class="image-wrap" style=""><img src="https://www.knowage-suite.com/jira/secure/attachment/10120/10120_image-2018-03-02-12-52-58-665.png" style="border: 0px solid black" /></span></p>

<p>Also i perfomed the tests with firewall rules deactivated and skype closed.</p>

<p>Could you please help me with this error?</p>

<p>BR,</p>

<p> </p>
<i>[KNOW-72] created by danielamgarat</i>

**Comment by anbernabei** [comment]
Hi
we've not able to replicate on Knowage 6.2
For us is fixed

best Regards
Angelo
