### ISSUE TITLE
Please add the Foodmart examples to PostgreSQL & Oracle

### ISSUE THREAD

**Issue by miniwark** [KnowageLabs/Knowage-Server#44]
Seems like than the Foodmart example is only available for MySQL/ MariaDB.

Would it be possible to port it to Postgres & oracle ?

By the way, the foodmart.sql script is available inside the Knowage_CE installer, but not here on Github.

**Comment by anbernabei** [comment]
Dear Bertrand,
We are using foodmart only to create a simple demo on MySQL/MariaDB, actually we have no intectionto release a different demo using oracle or Postgress.
But it is easy to find application that load Foodmart on Oracle and PostgreSQL on the web,

Best Regards
Angelo
