### ISSUE TITLE
Update documentation for manual install of foo-commonj

### ISSUE THREAD

**Issue by miniwark** [KnowageLabs/Knowage-Server#45]
See https://github.com/KnowageLabs/Knowage-Server-Docker/issues/8

In short, `foo-commonj.jar` is not available where he used to be. Please update the documentation with a downlable link alternative.

**Comment by anbernabei** [comment]
Hi
We've just corrected
http://knowage-suite.readthedocs.io/en/latest/installation-guide/manual-installation.html#dependencies

Best Regards
Angelo
