### ISSUE TITLE
MetaWeb hibernate.cfg.xml does not update dialect for selected database

### ISSUE THREAD

**Issue by mxc** [KnowageLabs/Knowage-Server#46]
**Describe the bug**
Deploying the metaweb war file when using a datasource for the knowage database other than mysql results in the metaweb application never loading.

**To Reproduce**
1. Install Knowage.war
2. Configure Knowage to use the correct hibernate dialect (e.g postgresql)
3. Install MetaWeb.war
4. Attempt to create a BusinessModel
5. The application never loads and the following error is thrown:

> 30 Jul 2018 11:58:58,732 ERROR it.eng.knowage.meta.service.PageResource.getPage:206 - Error 

> during Metamodel initialization: it.eng.spagobi.commons.dao.SpagoBIDAOException: An unexpected error occured while loading active content for model with id [2]
> 30 Jul 2018 14:28:30,098 ERROR org.hibernate.util.JDBCExceptionReporter.logExceptions:234 - ERROR: operator does not exist: boolean = integer
>   Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
>   Position: 840
> 30 Jul 2018 14:28:30,099 ERROR it.eng.spagobi.commons.dao.AbstractHibernateDAO.logException:254 - org.hibernate.exception.SQLGrammarException could not execute query
> org.hibernate.exception.SQLGrammarException: could not execute query
>     at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:92)
>     at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:66)
>     at org.hibernate.loader.Loader.doList(Loader.java:2536)
>     at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2276)
>     at org.hibernate.loader.Loader.list(Loader.java:2271)
>     at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:452)
>     at org.hibernate.hql.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:363)
>     at org.hibernate.engine.query.HQLQueryPlan.performList(HQLQueryPlan.java:196)
>     at org.hibernate.impl.SessionImpl.list(SessionImpl.java:1268)
>     at org.hibernate.impl.QueryImpl.list(QueryImpl.java:102)
>     at org.hibernate.impl.AbstractQueryImpl.uniqueResult(AbstractQueryImpl.java:890)
>     at it.eng.spagobi.tools.catalogue.dao.MetaModelsDAOImpl.loadActiveMetaModelContentById(MetaModelsDAOImpl.java:839)
>     at it.eng.knowage.meta.service.PageResource.getPage(PageResource.java:143)
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke(Method.java:498)
>     at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:140)
>     at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:294)
>     at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:248)
>     at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:235)
>     at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:398)
>     at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:205)
>     at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:228)
>     at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
>     at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
>     at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
>     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
>     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
>     at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
>     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
>     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
>     at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
>     at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
>     at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496)
>     at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
>     at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
>     at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
>     at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
>     at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
>     at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
>     at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
>     at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
>     at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1460)
>     at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
>     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>     at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
>     at java.lang.Thread.run(Thread.java:748)
> Caused by: org.postgresql.util.PSQLException: ERROR: operator does not exist: boolean = integer
>   Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
>   Position: 840
>     at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2412)
>     at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2125)
>     at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:297)
>     at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
>     at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
>     at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:169)
>     at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:117)
>     at org.apache.tomcat.dbcp.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:82)
>     at org.apache.tomcat.dbcp.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:82)
>     at org.hibernate.jdbc.AbstractBatcher.getResultSet(AbstractBatcher.java:208)
>     at org.hibernate.loader.Loader.getResultSet(Loader.java:1953)
>     at org.hibernate.loader.Loader.doQuery(Loader.java:802)
>     at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:274)
>     at org.hibernate.loader.Loader.doList(Loader.java:2533)
>     ... 46 more
> 

**Expected behavior**
The MetaWeb application should deploy and work.

This can be fixed by editing the hibernate.cfg.xml file. Either the documentaitons should be updated or the application should use the hibernate dialect as set up in the knowage application.

**Comment by miniwark** [comment]
Just for clarification, (because i am in the same precess to use PostgreSQL)

1. By `MetaWeb.war` do you mean `knowagemeta.war` from `knowagemeta-bin-6_2_0-CE-20180719.zip` ?

2. The documentation, in the "manual install" section do actually say than `hibernate.cfg.xml` files must be edited to use the correct database dialect. Not only the `hibernate.cfg.xml` for the `knowage` webapp but also the one for `knowagemeta`  and a few other webapps. Look at [Configuration of the metadata db dialect](https://knowage-suite.readthedocs.io/en/latest/installation-guide/manual-installation.html#configuration-of-the-metadata-db-dialect)

3. Witch of the  `hibernate.cfg.xml` files did you have edited for fixing this ?

**Comment by anbernabei** [comment]
Hi
You have to change all hibernate.cfg.xml 
http://knowage-suite.readthedocs.io/en/latest/installation-guide/manual-installation.html#configuration-of-the-metadata-db-dialect

Best regards
A
