### ISSUE TITLE
Please open a security advisory

### ISSUE THREAD

**Issue by JLLeitschuh** [KnowageLabs/Knowage-Server#499]
Hello,
I'm an independent security researcher performing security research under the [GitHub Security Lab Bug Bounty Program](https://securitylab.github.com/).
I believe I may have found a security vulnerability in this project.

Please open a security advisory against this repository so we can privately discuss the details. This advisory can be opened by a user with admin permissions on this repository.

https://github.com/KnowageLabs/Knowage-Server/security/advisories 
Vulnerability disclosure will occur on Jul 28, 2022.

Currently, the details of the vulnerability are available here:

https://github.com/JLLeitschuh/security-research/security/advisories/GHSA-gg22-v4h2-cgp4

If you'd like to read the disclosure before opening an advisory, please respond to this issue with the GitHub usernames of the maintainers of this project and I'll add them to the advisory above.

**Comment by Redjaw** [comment]
Hello Jonathan,
we opened the advisory, you should have received the notification.

**Comment by JLLeitschuh** [comment]
I've added the contents of the advisory there! Thanks for your swift reply! 🙂

**Comment by Redjaw** [comment]
Thank you for the warning! Our internal security experts will take a look to your advisory soon!
