### ISSUE TITLE
As a demo_user I can not access PM -> KPI-Cards

### ISSUE THREAD

**Issue by WandreyRangon** [KnowageLabs/Knowage-Server#5]
As a demo_admin: all is fine, no problem

As a demo_user I can not access PM -> KPI-Cards
I can not access PM -> KPI-Cards
I get the following error message: 
HTTP Status 500
root cause:
The root cause of the error is: JSONObject["chart"] not found.
rg.apache.jasper.JasperException: An exception occurred processing JSP page /WEB-INF/jsp/kpiVisualization.jsp at line 57
54: <%
55: 	
56: 	JSONObject templateObj = engineInstance.getTemplate();
57: 	JSONObject chartObj = templateObj.getJSONObject("chart");
58: 	//JSONObject optionsObj = chartObj.getJSONObject("options");
59: 	String type = (String)chartObj.get("type");
60: 	// String model = (String)chartObj.get("model");
Console: xxxxx
Environment:
Oracle JVM1.8.0.x
Windows 10

**Comment by aportosa** [comment]
Dear WandreyRangon,
please report bugs by using our issue tracker: https://www.knowage-suite.com/jira
If you have any technical question, you can instead use out Q&A: https://www.knowage-suite.com/qa

Issue via Github will be disable soon.
