### ISSUE TITLE
Please explain the hmacKey parameter in server.xml

### ISSUE THREAD

**Issue by miniwark** [KnowageLabs/Knowage-Server#50]
The actual documentation for manual install did not ask to add in `server.xml` the line:
```xml
<Environment description="HMAC key" name="hmacKey" type="java.lang.String" value="abc123"/>
```
but his `hmacKey` line is added by the knowage_installer (and is also present in the many `context.xml` files).

1. please tell if this parameter is mandatory for Knowage CE
2. and what is it use

**Comment by miniwark** [comment]
I reply to myself, 

seems like it's explained in https://github.com/KnowageLabs/Knowage-Server/tree/master/doc/admin
- it's mandatory
- and it must be changed from default

This is not explained in https://github.com/KnowageLabs/Knowage-Documentation

So, the two docs must probably be merged together.

**Comment by aportosa** [comment]
We update the doc to include the hmacKey property.

See [this](https://github.com/KnowageLabs/Knowage-Documentation/pull/16) and [this](https://github.com/KnowageLabs/Knowage-Documentation/pull/17).
