### ISSUE TITLE
Add common-loggin as a dependencies requirement in the documentation

### ISSUE THREAD

**Issue by miniwark** [KnowageLabs/Knowage-Server#53]
`commons-logging.jar` & `commons-logging-api.jar` are both dependencies requirement for Knowage webaps. Without them, some webapps will not start (knowagekpiengine, knowagesvgviewerengine, 
knowagemeta, etc.

But, the [documentation](https://knowage-suite.readthedocs.io/en/latest/installation-guide/manual-installation.html)  only list _Apache Geronimo_, _Concurrency JSR-166_ and _aktivecortex-foo-commonj_

Please also add _commons-logging_ as a requirement in manual install documentation.

**Comment by aportosa** [comment]
Aktivecortex-foo-commonj requires such dependecies. We changed such dependecies to a different one.
 Please see [here](https://github.com/KnowageLabs/Knowage-Documentation/commit/9f144bf50c09e1326cfcd7344ab718a264425be1)
