### ISSUE TITLE
Add slj4j-api as a dependency requirement in the documentation 

### ISSUE THREAD

**Issue by miniwark** [KnowageLabs/Knowage-Server#54]
Since #45 and the recommended use of `aktivecortex-foo-commonj` fork in replacement to the `foo-commonj`,  the `slj4j-api` library seems to be a requirement for `aktivecortex-foo-commonj`.  (I am not sure if it was already the case for the original `foo-commonj` library).

Please update the documentation to add this library as a requirement in manual install.

PS: This may also be relevant to update the Docker; Chef and Installer projects accordingly.

**Comment by aportosa** [comment]
Closing this since we rolback to foo-commonj. See [this](https://github.com/KnowageLabs/Knowage-Server/issues/53).
