### ISSUE TITLE
spanish translation PR and request for contributions

### ISSUE THREAD

**Issue by johnfelipe** [KnowageLabs/Knowage-Server#572]
Hi dears, i PR spanish translation, pls review and accept
and tell me how can pull into my local instance and test

i want to contribute with my languages fr, de, it
But i want to figure like contributor user
Pls answer ASAP

**Comment by johnfelipe** [comment]
@Redjaw, can u guide me?

**Comment by Redjaw** [comment]
Sure! go in the PR you opened .
Copy the code from the Hint GitHub provided you, Just the "i have read..." Part in a new comment.
The automatic testing should start again and allow us to merge the request.
If that does not happen automatically, Just add another comment writing Just "recheck"

**Comment by johnfelipe** [comment]
one big contribution and nothing yet, what happend?

**Comment by Redjaw** [comment]
Hello, sorry but in our country it was the middle of the night.
Thank you very much for you contribution! It passed the automatic testing but not yet the CLA related ones as stated in our [readme](https://github.com/KnowageLabs/Knowage-Server#contributions).
We are going to review it and accept it as soon as possible. I'll hear from our licensing expert to understand why you cannot sign the licence agreement in github and let you know.

**Comment by johnfelipe** [comment]
can u help me about docker or commands for upload all demos in online to my
local environment?

**Comment by Redjaw** [comment]
To make the CLA sign work just write the comment like @kerny3d did in this PR #579 

Be sure to write just the content of the CLA request, without quotes or other text please.

The docker related questions will be answered in the related issue. #576

**Comment by Redjaw** [comment]
Good news, we made the CLA work with your latest comments.
Now we merged your PR and you will find yourself in the contributors list.
We will also update soon the same list on our [website](https://www.knowage-suite.com/site/licensing/community-edition/), if you want you can tell us your origin country so we can add it.

Thank you again for your patience and community contribution!

**Comment by johnfelipe** [comment]
Colombian

**Comment by johnfelipe** [comment]
@Redjaw how can pull my recent local env, for test my language contribution?

**Comment by Redjaw** [comment]
If you forked the project, Just update It to master.
If you run It locally remember you have to build the Vue project again.
Go in the knowage-vue folder, run `npm install` and `npm run serve`.
You can also wait for next release on docker.

**Comment by johnfelipe** [comment]
> 

pls tell me steps for create docker, i can help with that each time when translations update

**Comment by johnfelipe** [comment]
About docker??

**Comment by Redjaw** [comment]
For docker related instructions and issues I suggest you the specific [repository](https://github.com/KnowageLabs/Knowage-Server-Docker) and [documentation](https://github.com/KnowageLabs/Knowage-Server-Docker/blob/master/Knowage-Server-Docker/README.md). 

You Will find needed informations there.
Regards

**Comment by johnfelipe** [comment]
How can create temporal release of docker image?

**Comment by johnfelipe** [comment]
@Redjaw can u guide me for create a docker with latest features and translations?

**Comment by johnfelipe** [comment]
> @Redjaw can u guide me for create a docker with latest features and translations?

pls help me in this 
tnks

**Comment by Redjaw** [comment]
hello, 
I already shared what I knew in the #576 .
For docker related issues please refer to the specific [repository](https://github.com/KnowageLabs/Knowage-Server-Docker).
