### ISSUE TITLE
Can u give me a method for upload test demo, same like online version

### ISSUE THREAD

**Issue by johnfelipe** [KnowageLabs/Knowage-Server#576]
im research metabase. superset and others, superset upload demos very complete, can u guide me for upload demos to knowage?

**Comment by Redjaw** [comment]
Hi, can you explain us what your goal is?
There are different approach we can take depending on what you are willing to do:

- You can use the installer that will create you all the needed stack (DB, tomcat).
- You can build yourself locally the application from the github code or with docker
- You can PR the changes and test them on one of our updated environments

**Comment by johnfelipe** [comment]
No bro, I want demos online in my local installation, pls.

**Comment by Redjaw** [comment]
Which demos are you talking about? The ones available in the knowage demo environment? 
https://demo.knowage-suite.com/knowage

**Comment by johnfelipe** [comment]
Yes all of it
In my local environment, help me with that
Today I will upload rest of translations
But need to help with demos

**Comment by Redjaw** [comment]
I Think you Will need a dump of our metà demo db and you should have an Oracle instance in your local env. 
Using the installer should be more Quick, those documents are already present there.
But If you Need It I Will ask for the demo dump to our devops, It Will be available on monday I Guess.

**Comment by johnfelipe** [comment]
pls
wich version of Oracle?
im already have installed server from scratch, but will be a good collab
that demo dump
Pls tell me version of Oracle for install in my local server

**Comment by Redjaw** [comment]
I suggest you 12, but use One of the [certified ones](https://knowage-suite.readthedocs.io/en/7.4/installation-guide/requirements.html?highlight=oracle#database-schema-for-metadata).
Remember to add the JDBC driver as reported [here](https://www.knowage-suite.com/qa/5005/connect-to-oracle-database)

**Comment by johnfelipe** [comment]
> I suggest you 12, but use One of the [certified ones](https://knowage-suite.readthedocs.io/en/7.4/installation-guide/requirements.html?highlight=oracle#database-schema-for-metadata). Remember to add the JDBC driver as reported [here](https://www.knowage-suite.com/qa/5005/connect-to-oracle-database)

```
[root@felipeurrego2 sqlpad-oracle]# sqlplus system/oracle@//localhost:1521/xe

SQL*Plus: Release 12.2.0.1.0 Production on Fri Jun 10 18:23:29 2022

Copyright (c) 1982, 2016, Oracle.  All rights reserved.


Connected to:
Oracle Database 12c Standard Edition Release 12.2.0.1.0 - 64bit Production

SQL>

```

ready installed oracle 12, like you suggest me, but my question now is how 

`Remember to add the JDBC driver`

**Comment by johnfelipe** [comment]
Ho dear pls remember dumb of oracle database and method for restore in knowage

**Comment by Redjaw** [comment]
Hello,
for the restore I do use DBeaver, but honestly you can use the tool you do prefere. Take the dump and use the restore feature from your tool (is different for each one).
In docker the tomcat folder is /opt/knowage/apache-tomcat, you will find the server.xml there too.

Watch out, to make your local changes appear (I see you are not just searching for demo data) remember that you have to create the new war packages at least for the knowage-vue project. To do so get inside the knowage-vue folder on your cloned installation and run `mvn clean install`. If you do have maven installed you should then see a new knowage-vue.war file. You can replace it in your docker to make it work.

Hope that helps.
For docker related issues, please ask in the related repository. You will have more details there.

**Comment by johnfelipe** [comment]
```
DB_HOST=knowagedb
DB_PORT=3306
DB_DB=knowagedb
DB_USER=knowageuser
DB_PASS=knowagepassword
CACHE_DB_HOST=knowagecache
CACHE_DB_PORT=3306
CACHE_DB_DB=knowagecache
CACHE_DB_USER=knowageuser
CACHE_DB_PASS=knowagepassword
HMAC_KEY=abc123
PASSWORD_ENCRYPTION_SECRET=def456
```

but pls view this video:

https://drive.google.com/file/d/1n_FhlfoOx5B7WU6cnRO3boXQitHvvGor/view?usp=drivesdk

i cant connect

**Comment by johnfelipe** [comment]
pls help me with my issue

**Comment by kerny3d** [comment]
Hi @johnfelipe,

have you seen my previous comment?

https://github.com/KnowageLabs/Knowage-Server/issues/576#issuecomment-1160474811

You cannot use knowagedb outside a Docker container.

**Comment by johnfelipe** [comment]
yes dear, and works. i mean i can access with dbear, but i cant restore dumb

**Comment by johnfelipe** [comment]
https://github.com/KnowageLabs/Knowage-Server/issues/576#issuecomment-1160491475

**Comment by kerny3d** [comment]
Ok, open the dump with a text editor like Notepad++, for example. 

Replace "utf8mb4_0900_ai_ci" with "utf8mb4_general_ci". Our DB was created in an older version.

**Comment by johnfelipe** [comment]
this error show with all replacement

```
C:\Users\GAMEMAX\AppData\Roaming\DBeaverData\drivers\clients\mysql\win\mysql.exe -u knowageuser --host=192.168.0.18 --port=3306 -v knowagedb
Task 'MySQL restore' started at Tue Jun 21 07:47:25 COT 2022
--------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */

--------------



--------------

/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */

--------------



--------------

/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */

--------------



--------------

/*!50503 SET NAMES utf8mb4 */

--------------



--------------

/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */

--------------



--------------

/*!40103 SET TIME_ZONE='+00:00' */

--------------



--------------

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */

--------------



--------------

/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */

--------------



--------------

/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */

--------------



--------------

/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */

--------------



--------------

DROP TABLE IF EXISTS `DATABASECHANGELOG`

--------------



--------------

/*!40101 SET @saved_cs_client     = @@character_set_client */

--------------



--------------

/*!50503 SET character_set_client = utf8mb4 */

--------------



--------------

CREATE TABLE `DATABASECHANGELOG` (

  `ID` varchar(255) NOT NULL,

  `AUTHOR` varchar(255) NOT NULL,

  `FILENAME` varchar(255) NOT NULL,

  `DATEEXECUTED` datetime NOT NULL,

  `ORDEREXECUTED` int NOT NULL,

  `EXECTYPE` varchar(10) NOT NULL,

  `MD5SUM` varchar(35) DEFAULT NULL,

  `DESCRIPTION` varchar(255) DEFAULT NULL,

  `COMMENTS` varchar(255) DEFAULT NULL,

  `TAG` varchar(255) DEFAULT NULL,

  `LIQUIBASE` varchar(20) DEFAULT NULL,

  `CONTEXTS` varchar(255) DEFAULT NULL,

  `LABELS` varchar(255) DEFAULT NULL,

  `DEPLOYMENT_ID` varchar(10) DEFAULT NULL

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci

--------------



--------------

/*!40101 SET character_set_client = @saved_cs_client */

--------------



--------------

LOCK TABLES `DATABASECHANGELOG` WRITE

--------------



--------------

/*!40000 ALTER TABLE `DATABASECHANGELOG` DISABLE KEYS */

--------------



--------------

/*!40000 ALTER TABLE `DATABASECHANGELOG` ENABLE KEYS */

--------------



--------------

UNLOCK TABLES

--------------



--------------

DROP TABLE IF EXISTS `DATABASECHANGELOGLOCK`

--------------



--------------

/*!40101 SET @saved_cs_client     = @@character_set_client */

--------------



--------------

/*!50503 SET character_set_client = utf8mb4 */

--------------



--------------

CREATE TABLE `DATABASECHANGELOGLOCK` (

  `ID` int NOT NULL,

  `LOCKED` bit(1) NOT NULL,

  `LOCKGRANTED` datetime DEFAULT NULL,

  `LOCKEDBY` varchar(255) DEFAULT NULL,

  PRIMARY KEY (`ID`)

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci

--------------



--------------

/*!40101 SET character_set_client = @saved_cs_client */

--------------



--------------

LOCK TABLES `DATABASECHANGELOGLOCK` WRITE

--------------



--------------

/*!40000 ALTER TABLE `DATABASECHANGELOGLOCK` DISABLE KEYS */

--------------



--------------

INSERT INTO `DATABASECHANGELOGLOCK` VALUES (1,0x00,NULL,NULL)

--------------



--------------

/*!40000 ALTER TABLE `DATABASECHANGELOGLOCK` ENABLE KEYS */

--------------



--------------

UNLOCK TABLES

--------------



--------------

DROP TABLE IF EXISTS `QRTZ_BLOB_TRIGGERS`

--------------



--------------

/*!40101 SET @saved_cs_client     = @@character_set_client */

--------------



--------------

/*!50503 SET character_set_client = utf8mb4 */

--------------



--------------

CREATE TABLE `QRTZ_BLOB_TRIGGERS` (

  `TRIGGER_NAME` varchar(120) COLLATE utf8mb4_general_ci NOT NULL,

  `TRIGGER_GROUP` varchar(120) COLLATE utf8mb4_general_ci NOT NULL,

  `BLOB_DATA` blob,

  `SCHED_NAME` varchar(120) COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'DefaultQuartzScheduler',

  PRIMARY KEY (`SCHED_NAME`,`TRIGGER_NAME`,`TRIGGER_GROUP`),

  KEY `TRIGGER_NAME` (`TRIGGER_NAME`,`TRIGGER_GROUP`),

  CONSTRAINT `QRTZ_BLOB_TRIGGERS_ibfk_1` FOREIGN KEY (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`) REFERENCES `QRTZ_TRIGGERS` (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`)

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci

-------ERROR 1005 (HY000) at line 85: Can't create table `knowagedb`.`QRTZ_BLOB_TRIGGERS` (errno: 150 "Foreign key constraint is incorrectly formed")

-------



Task 'MySQL restore' finished at Tue Jun 21 07:47:25 COT 2022
2022-06-21 07:47:25.922 - IO error: Process failed (exit code = 1). See error log.
2022-06-21 07:47:25.923 - java.io.IOException: Process failed (exit code = 1). See error log.
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.validateErrorCode(AbstractNativeToolHandler.java:242)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.executeProcess(AbstractNativeToolHandler.java:223)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.doExecute(AbstractNativeToolHandler.java:262)
	at org.jkiss.dbeaver.ext.mysql.tasks.MySQLNativeToolHandler.doExecute(MySQLNativeToolHandler.java:47)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.lambda$0(AbstractNativeToolHandler.java:83)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

```

**Comment by johnfelipe** [comment]
may be if u share a new dump?

**Comment by johnfelipe** [comment]
dear pls help me for show to clients power of knowage with that demo data

**Comment by kerny3d** [comment]
Hi,

[here](https://drive.google.com/file/d/1lSCjhMurkHYGZgB4E13pQhbH-S8yVqgU/view?usp=sharing) you can find the new and fixed DB dump.

I've tested it on both MySQL and MariaDB.

**Comment by johnfelipe** [comment]
still error with dbeaver 22.1.0

![SNAG-0009](https://user-images.githubusercontent.com/428820/175309268-5e59bed0-8225-41c0-b2b9-4dcffebb287b.png)

how solve this?

**Comment by johnfelipe** [comment]
![SNAG-0010](https://user-images.githubusercontent.com/428820/175310263-33592a82-c376-44f0-bd3e-a67a24e518b8.png)

change again engine?

**Comment by kerny3d** [comment]
Which user are you using in DBeaver?

**Comment by johnfelipe** [comment]
```
192.168.0.18
knowagedb
knowageuser
knowagepassword

```

**Comment by johnfelipe** [comment]
i bro, me again, any solution?

**Comment by kerny3d** [comment]
I'm looking for some solution. I need some time.

**Comment by johnfelipe** [comment]
I already ready setup oracle
Don't worry for licence
Because I want to show for my university and change cloudera and begin with
a stack with, Cassandra, Hadoop, spark, airflow and metabase and change all
streaming with knowage.

Pls add like contributor pls

Mgtr Felipe Urrego
Tnks

**Comment by johnfelipe** [comment]
Hi dear any progress??

**Comment by johnfelipe** [comment]
Hi dear, nothing yet?

**Comment by johnfelipe** [comment]
hi my pal, any advance?

**Comment by johnfelipe** [comment]
@kerny3d pls tell me if u have solution
tnks

**Comment by kerny3d** [comment]
I need some time to prepare an image of the DB with the demo resources. This is the only solution I could think of.

**Comment by johnfelipe** [comment]
what kind of error or information private of actual DB image?
remember only i need show why this is better of superset or metabase, even cloudera, pls hurry up
tnks

**Comment by johnfelipe** [comment]
Dear what about if you share demos in oracle like first attempt?

**Comment by johnfelipe** [comment]
any news dear?

**Comment by johnfelipe** [comment]
Nothing yet?

**Comment by johnfelipe** [comment]
hi dear, i need quick solution for take knowage like BI software, pls hurry up

**Comment by johnfelipe** [comment]
Dear, me again, pls tell me how % of completion have, share a demo of demo portal???

**Comment by johnfelipe** [comment]
Hi pal, nothing yet?

**Comment by johnfelipe** [comment]
Dear I'm counting with your help....

**Comment by johnfelipe** [comment]
R u in vacation?

**Comment by johnfelipe** [comment]
> I need some time to prepare an image of the DB with the demo resources. This is the only solution I could think of.

hi dear, any progress about this?

**Comment by johnfelipe** [comment]
Hi my pal, pls help me

**Comment by johnfelipe** [comment]
Hi pal, pls guide me into actual version of database, I think university will go with tableau, but i need show this app with demos, plssss

**Comment by johnfelipe** [comment]
Anyone?

**Comment by johnfelipe** [comment]
> I need some time to prepare an image of the DB with the demo resources. This is the only solution I could think of.

Dear anything?

**Comment by johnfelipe** [comment]
Pls don't delete files for a couple of days, I will test and request your
help if I need
Tnks a lot

**Comment by johnfelipe** [comment]
Hi dear, any progress?

**Comment by johnfelipe** [comment]
Hi dear is possible deploy an instance with demo data?

**Comment by johnfelipe** [comment]
Still need this help...
