### ISSUE TITLE
As a demo_user I can not access PA -> WHAT-IF 

### ISSUE THREAD

**Issue by WandreyRangon** [KnowageLabs/Knowage-Server#6]
As a demo_admin: all is fine, no problem
I can't access PA -> WHAT-IF 
I get the following error message:
"Impossible to get template's content
Description: Impossible to get template's content: There are no template associated to document [2477] 
How to fix it: 
Check the document's template"

Environment:
Oracle JVM1.8.0.x
Windows 10

**Comment by WandreyRangon** [comment]
LI -> Sales map "File not found" with  demo_user and demo_admin roles.
File not found
Testing Knowage-6.0.0-CE-Installer-Windows-JVM64bit-20170616.exe

**Comment by aportosa** [comment]
Dear frank-dkvan,
please report bugs by using our issue tracker: https://www.knowage-suite.com/jira
If you have any technical question, you can instead use out Q&A: https://www.knowage-suite.com/qa

Issue via Github will be disable soon.
