### ISSUE TITLE
Javascript error at OLAP template building when trying to select another measure

### ISSUE THREAD

**Issue by samueldc** [KnowageLabs/Knowage-Server#618]
**Describe the bug**

I'm new to Knowage. Not sure if it's a bug. But mondrian squema works fine at Pentaho BI Server. Trying to follow the [documentation about OLAP template building](https://knowage-suite.readthedocs.io/en/8.0/functionalities-guide/multidimensional-analysis/index.html#creation-of-an-olap-document). When trying to select another query measure and apply, the page freezes. Inspecting we see the following javascript error messages in the console:

```
TypeError: Cannot read properties of null (reading 'wrappedObject')
    at Proxy.loadLevelValues (OlapFilterDialog.vue:69:64)
    at Proxy.loadLevels (OlapFilterDialog.vue:66:18)
    at Proxy.loadFilter (OlapFilterDialog.vue:53:18)
    at Proxy.propFilter (OlapFilterDialog.vue:44:18)
    at Pe (runtime-core.esm-bundler.js:154:22)
    at Ie (runtime-core.esm-bundler.js:163:21)
    at Array.b (runtime-core.esm-bundler.js:2032:17)
    at st (runtime-core.esm-bundler.js:329:31)
    at F (runtime-core.esm-bundler.js:5303:9)
    at runtime-core.esm-bundler.js:5231:21
```
```
TypeError: Cannot read properties of null (reading 'wrappedObject')
    at Proxy.updateOlapDesignerMDXQueryParameters (Olap.vue:816:40)
    at Olap.vue:805:22
    at c (runtime.js:63:40)
    at Generator._invoke (runtime.js:293:22)
    at Generator.next (runtime.js:118:21)
    at r (asyncToGenerator.js:3:20)
    at s (asyncToGenerator.js:25:9)
```

After refreshing the page, the measure is added and page returns to normal (refreshing only works at open designer page). After refreshing on execution page all changes are lost.

The same error occurs both at the open designer page and the execution page.

**To Reproduce**

1. Edit a OLAP document and click on open designer or execute it.
2. Click on the measures filter icon and try to add another measure.
3. Check if the page freezes.
4. Inspect the page and check javascript error at the console.

**Expected behavior**

Add another measure to the query without errors nor freezing the page.

**Screenshots**

Screenshots attached.

![KnowageScreen01](https://user-images.githubusercontent.com/1208323/180256697-d13dfac6-f04e-46b2-9eaf-9a2021e67dbd.JPG)

![KnowageScreen02](https://user-images.githubusercontent.com/1208323/180256727-35dcda9e-e7e7-41ca-8646-a7dfdeffffee.JPG)

![KnowageScreen03](https://user-images.githubusercontent.com/1208323/180256744-43d0117e-bb49-4c94-b429-00d9bf39b829.JPG)

**Desktop (please complete the following information):**

 - OS: Windows 10 | WSL2 | Docker
 - Browser: Chrome
 - Version: Knowage 8.1

[otrs-olap.zip](https://github.com/KnowageLabs/Knowage-Server/files/9160797/otrs-olap.zip)

**Additional context**

Mondrian schema and document template also attached.

**Comment by Redjaw** [comment]
Hi, thank you for the detailed issue, we will investigate and let you know.
Based on the console you shared I suppose it's a bug.

**Comment by samueldc** [comment]
Was the issue solved in a newer version?
