### ISSUE TITLE
How to use InteIIij IDEA to run this project

### ISSUE THREAD

**Issue by njitjiang** [KnowageLabs/Knowage-Server#62]
How to use InteIIij IDEA to run this project? thanks!

**Comment by gclsoft** [comment]
@njitjiang Have you solved it?

**Comment by fralucch** [comment]
Hi, open project knowage-ce-parent as a Maven project, all other projects will be imported as modules

**Comment by njitjiang** [comment]
> 
> 
> Hi, open project knowage-ce-parent as a Maven project, all other projects will be imported as modules

thanks very much，you are right!  it is a first step,the second is choose a Tomcat and must chooose all war file
![default](https://user-images.githubusercontent.com/12026119/48926725-64d29080-ef0b-11e8-9df7-cc7fe24abf78.png)

**Comment by TRaouf** [comment]
Hi, 
And where do war files come from, do you need to download them first.
Can you provide more details please.
