### ISSUE TITLE
How to fix rest Api dataset metadata error

### ISSUE THREAD

**Issue by yusufuzunkafein** [KnowageLabs/Knowage-Server#640]
Hi,

When I want to add rest api we get an error. We are using version 8.1 but 7.2 version works fine. How can fix this issue ?

![image](https://user-images.githubusercontent.com/70193138/189831309-20eb610d-78d4-4b4f-83d9-9f985202e527.png)

Exception detail;

`ERROR [http-nio-8080-exec-3] [it.eng.spagobi.tools.dataset.service.ManageDataSetsForREST.getGuiGenericDatasetToInsert:439] [97ef16e1-823c-4168-b3fd-59c1a4b1263a] [] [DEFAULT_TENANT]`

`Error while updating dataset metadata, cannot save the dataset org.json.JSONException: No content to map due to end-of-input at [Source: (String)""; line: 1, column: 0] at org.json.JSONArray.(JSONArray.java:65) ~[knowage-utils-json-8.1.1-SNAPSHOT.jar:8.1.1-SNAPSHOT] at it.eng.spagobi.tools.dataset.service.ManageDataSetsForREST.manageRESTDataSet(ManageDataSetsForREST.java:1536) ~[knowage-core-8.1.1-SNAPSHOT.jar:8.1.1-SNAPSHOT] at it.eng.spagobi.tools.dataset.service.ManageDataSetsForREST.getDataSet(ManageDataSetsForREST.java:524) ~[knowage-core-8.1.1-SNAPSHOT.jar:8.1.1-SNAPSHOT] at it.eng.spagobi.tools.dataset.service.ManageDataSetsForREST.getGuiGenericDatasetToInsert(ManageDataSetsForREST.java:230) ~[knowage-core-8.1.1-SNAPSHOT.jar:8.1.1-SNAPSHOT] at it.eng.spagobi.tools.dataset.service.ManageDataSetsForREST.datasetInsert(ManageDataSetsForREST.java:181) ~[knowage-core-8.1.1-SNAPSHOT.jar:8.1.1-SNAPSHOT] at it.eng.spagobi.tools.dataset.service.ManageDataSetsForREST.insertDataset(ManageDataSetsForREST.java:177) ~[knowage-core-8.1.1-SNAPSHOT.jar:8.1.1-SNAPSHOT] at it.eng.spagobi.api.DataSetResource.persistDataSets(DataSetResource.java:830) ~[knowage-core-8.1.1-SNAPSHOT.jar:8.1.1-SNAPSHOT] at sun.reflect.GeneratedMethodAccessor474.invoke(Unknown Source) ~[?:?] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265] at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265] at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:139) ~[resteasy-jaxrs-3.6.2.Final.jar:3.6.2.Final] at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:509) ~[resteasy-jaxrs-3.6.2.Final.jar:3.6.2.Final] at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:399) ~[resteasy-jaxrs-3.6.2.Final.jar:3.6.2.Final] at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$0(ResourceMethodInvoker.java:363) ~[resteasy-jaxrs-3.6.2.Final.jar:3.6.2.Final] at org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:355) ~[resteasy-jaxrs-3.6.2.Final.jar:3.6.2.Final] at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:365) ~[resteasy-jaxrs-3.6.2.Final.jar:3.6.2.Final] at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:337) ~[resteasy-jaxrs-3.6.2.Final.jar:3.6.2.Final] at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:310) ~[resteasy-jaxrs-3.6.2.Final.jar:3.6.2.Final] at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:439) ~[resteasy-jaxrs-3.6.2.Final.jar:3.6.2.Final] at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:229) ~[resteasy-jaxrs-3.6.2.Final.jar:3.6.2.Final] at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:135) ~[resteasy-jaxrs-3.6.2.Final.jar:3.6.2.Final] at org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:355) ~[resteasy-jaxrs-3.6.2.Final.jar:3.6.2.Final] at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:138) ~[resteasy-jaxrs-3.6.2.Final.jar:3.6.2.Final] at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:215) ~[resteasy-jaxrs-3.6.2.Final.jar:3.6.2.Final] at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:227) ~[resteasy-jaxrs-3.6.2.Final.jar:3.6.2.Final] at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56) ~[resteasy-jaxrs-3.6.2.Final.jar:3.6.2.Final] at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51) ~[resteasy-jaxrs-3.6.2.Final.jar:3.6.2.Final] at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) ~[servlet-api.jar:4.0.FR] at sun.reflect.GeneratedMethodAccessor410.invoke(Unknown Source) ~[?:?] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265] at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265] at org.apache.catalina.security.SecurityUtil.lambda$execute$0(SecurityUtil.java:280) ~[catalina.jar:9.0.60] at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_265] at javax.security.auth.Subject.doAsPrivileged(Subject.java:549) ~[?:1.8.0_265] at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:311) ~[catalina.jar:9.0.60] at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:170) ~[catalina.jar:9.0.60] at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:221) ~[catalina.jar:9.0.60] at org.apache.catalina.core.ApplicationFilterChain.lambda$doFilter$0(ApplicationFilterChain.java:145) ~[catalina.jar:9.0.60] at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_265] at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:143) ~[catalina.jar:9.0.60] at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-websocket.jar:9.0.60] at sun.reflect.GeneratedMethodAccessor408.invoke(Unknown Source) ~[?:?] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265] at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265] at org.apache.catalina.security.SecurityUtil.lambda$execute$0(SecurityUtil.java:280) ~[catalina.jar:9.0.60] at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_265] at javax.security.auth.Subject.doAsPrivileged(Subject.java:549) ~[?:1.8.0_265] at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:311) ~[catalina.jar:9.0.60] at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:253) ~[catalina.jar:9.0.60] at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:187) ~[catalina.jar:9.0.60] at org.apache.catalina.core.ApplicationFilterChain.lambda$doFilter$0(ApplicationFilterChain.java:145) ~[catalina.jar:9.0.60] at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_265] at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:143) ~[catalina.jar:9.0.60] at it.eng.knowage.utils.filters.LoggerSetupFilter.doFilter(LoggerSetupFilter.java:45) ~[knowage-utils-8.1.1-SNAPSHOT.jar:8.1.1-SNAPSHOT] at sun.reflect.GeneratedMethodAccessor408.invoke(Unknown Source) ~[?:?] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265] at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265] at org.apache.catalina.security.SecurityUtil.lambda$execute$0(SecurityUtil.java:280) ~[catalina.jar:9.0.60] at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_265] at javax.security.auth.Subject.doAsPrivileged(Subject.java:549) ~[?:1.8.0_265] at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:311) ~[catalina.jar:9.0.60] at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:253) ~[catalina.jar:9.0.60] at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:187) ~[catalina.jar:9.0.60] at org.apache.catalina.core.ApplicationFilterChain.lambda$doFilter$0(ApplicationFilterChain.java:145) ~[catalina.jar:9.0.60] at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_265] at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:143) ~[catalina.jar:9.0.60] at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71) ~[log4j-web-2.17.1.jar:2.17.1] at sun.reflect.GeneratedMethodAccessor408.invoke(Unknown Source) ~[?:?] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265] at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265] at org.apache.catalina.security.SecurityUtil.lambda$execute$0(SecurityUtil.java:280) ~[catalina.jar:9.0.60] at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_265] at javax.security.auth.Subject.doAsPrivileged(Subject.java:549) ~[?:1.8.0_265] at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:311) ~[catalina.jar:9.0.60] at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:253) ~[catalina.jar:9.0.60] at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:187) ~[catalina.jar:9.0.60] at org.apache.catalina.core.ApplicationFilterChain.lambda$doFilter$0(ApplicationFilterChain.java:145) ~[catalina.jar:9.0.60] at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_265] at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:143) [catalina.jar:9.0.60] at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197) [catalina.jar:9.0.60] at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) [catalina.jar:9.0.60] at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) [catalina.jar:9.0.60] at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) [catalina.jar:9.0.60] at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [catalina.jar:9.0.60] at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687) [catalina.jar:9.0.60] at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) [catalina.jar:9.0.60] at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360) [catalina.jar:9.0.60] at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399) [tomcat-coyote.jar:9.0.60] at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-coyote.jar:9.0.60] at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:889) [tomcat-coyote.jar:9.0.60] at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1743) [tomcat-coyote.jar:9.0.60] at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:9.0.60] at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) [tomcat-util.jar:9.0.60] at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) [tomcat-util.jar:9.0.60] at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.60] at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]`

**Comment by ttutuncu** [comment]
@Redjaw is there any quick fix for this bug?

**Comment by Redjaw** [comment]
There is no quick fix for this bug. 
We are going to push a solution soon in the next few days, I will link the commit here.

**Comment by kerny3d** [comment]
For master, see commits:

- https://github.com/KnowageLabs/Knowage-Server/commit/0c4e2f35afe256433f6b225cf3226256c562e564
- https://github.com/KnowageLabs/Knowage-Server/commit/63ad49564513faa40f12eb06bd47e4250c698bf9

For 8.1, see commits:

- https://github.com/KnowageLabs/Knowage-Server/commit/5f4904b6c3d6ffdea4687cbafe383387bfa20995
- https://github.com/KnowageLabs/Knowage-Server/commit/bfeafc55dd04f8e953473c559c5631dec2ed273f

The fix will be available in the 8.1.1 and 8.2.0.

**Comment by ahmtklmkfn** [comment]
I still get the error when I try the latest version of the master branch. Haven't you merged your changes with the master branch yet?
