### ISSUE TITLE
[MUST] Credits are missing

### ISSUE THREAD

**Issue by jason-fox** [KnowageLabs/Knowage-Server#69]
According to the contribution requirements, credit must be given to developers who contribute to the development of each component. A simple way to do this is to add and maintain a  [CREDITS](https://github.com/Engineering-Research-and-Development/iotagent-opcua/blob/master/CREDITS) file.

The list of previous contributors can be obtained using the following command:

```console
git shortlog -cse
```

- MUST Requirement from the TSC

**Comment by fralucch** [comment]
Done
