### ISSUE TITLE
function "dataset management" doesn't support UTF-8, showing "?????" instead of correct Chinese string

### ISSUE THREAD

**Issue by frank-dkvan** [KnowageLabs/Knowage-Server#7]
after I create a new dataset and import an excel file, the function field  "description" shows "??????" instead of Chinese string, and the function "field metadata" show "dataset field name" with "?????" instead of  Chinese name as well.  it's maybe an encoding problem.      I can not fixed it because I can not import source code into Eclipse correctly since the projects haven't been maven-ized yet.

**Comment by aportosa** [comment]
Dear frank-dkvan, 
please report bugs by using our issue tracker: https://www.knowage-suite.com/jira

Issue via Github will be disable soon.
