### ISSUE TITLE
How to fix Rest Api data set saving problem ?

### ISSUE THREAD

**Issue by ahmtklmkfn** [KnowageLabs/Knowage-Server#707]
Hi,

When I want to add rest api data set ı get an error. When I examined github issues, a bug was opened about it. I also checked the answers you gave. You said you fixed the problem and I can see the changes you made. I still get the error when I try the latest version of the master branch. Haven't you merged your changes with the master branch yet?

**Comment by hackCHM123** [comment]
How to handle this error ？
![Snipaste_2022-12-16_16-56-07](https://user-images.githubusercontent.com/28669125/208061352-00a8dc6e-0947-4227-a41f-05cdfb1e67a4.png)

**Comment by kerny3d** [comment]
Hi @ahmtklmkfn,

could you attach the knowage.log you should find in logs directory inside Tomcat folder?

@hackCHM123, is your comment related to this thread? Because in your screenshot I see a unit test non related the problem of  ahmtklmkfn.

**Comment by ahmtklmkfn** [comment]
Hi @kerny3d 

I see that a task has been opened before about this error. And I saw in the answers given that it will be fixed in version 8.1.1. When will you share versions after Knowage 8.1
