### ISSUE TITLE
[MUST] Default content missing from README

### ISSUE THREAD

**Issue by jason-fox** [KnowageLabs/Knowage-Server#72]
For standardization and convenience, the `README` is encouraged to follow [Standard-readme](https://github.com/RichardLitt/standard-readme) or similar, the readme is currently missing a few mandatory sections, compare with [this](https://github.com/telefonicaid/iotagent-json/blob/master/README.md) which is compact, but has full compliance.

*  No Table of contents
*  No text on how to run unit tests
*  No text on main **Usage** of the component
*  No text on how to **Install** the component

**Comment by davide-zerbetto** [comment]
Missing sections were added.
