### ISSUE TITLE
[MUST] Use open source dependencies

### ISSUE THREAD

**Issue by jason-fox** [KnowageLabs/Knowage-Server#73]
Several dependencies have been identified which do not have a `LICENSE` and therefore need to be removed or updated to licensed components:

```
github.com/KnowageLabs/Knowage-Server  org.pivot4j:pivot4j-core  Avalon Framework API
github.com/KnowageLabs/Knowage-Server  org.pivot4j:pivot4j-core  Avalon Framework Implementation
github.com/KnowageLabs/Knowage-Server  axis-wsdl4j
github.com/KnowageLabs/Knowage-Server  JAMon Core
github.com/KnowageLabs/Knowage-Server  https://nexus.pentaho.org/content/groups/omni:pentaho:mondrian  commons-vfs
github.com/KnowageLabs/Knowage-Server  https://nexus.pentaho.org/content/groups/omni:pentaho:mondrian  javacup
github.com/KnowageLabs/Knowage-Server  org.jasig.cas:cas-server-core  opensaml
github.com/KnowageLabs/Knowage-Server  jaxrpc
github.com/KnowageLabs/Knowage-Server  org.jasig.cas:cas-server-core  JSR 105 - Java(TM) XML Digital Signature API
github.com/KnowageLabs/Knowage-Server  org.eclipse.birt.runtime:org.eclipse.birt.runtime flute
github.com/KnowageLabs/Knowage-Server  org.eclipse.persistence:eclipselink  SDO API
github.com/KnowageLabs/Knowage-Server  org.springframework.security:spring-security-cas-client  JA-SIG CAS Client for Java - Core
github.com/KnowageLabs/Knowage-Server  JA-SIG CAS Core
```

Elements without a `LICENSE` are technically _All rights reserved_ and should not be used in Open Source

- MUST requirement from the TSC

**Comment by davide-zerbetto** [comment]
After analyzing those dependencies, we found out that they are open source libraries: 

Avalan Framework is licensed under Apache license: the following files contain LICENSE.txt file with Apache License 2.0:
http://central.maven.org/maven2/avalon-framework/avalon-framework-api/4.2.0/avalon-framework-api-4.2.0.jar
http://central.maven.org/maven2/avalon-framework/avalon-framework-impl/4.2.0/avalon-framework-impl-4.2.0.jar

axis-wsdl4j library is this one:
https://sourceforge.net/projects/wsdl4j/files/WSDL4J/1.5.1/wsdl4j-bin-1.5.1.zip/download
and it is licensed under the CPL 1.0 license, as you can see from here:
https://sourceforge.net/projects/wsdl4j/
or from the license file that is included in the zip file.

JAMon is licensed under the JAMon License Agreement license, as you can see from here:
http://jamonapi.sourceforge.net/JAMonLicense.html

commons-vfs library should come from here:
https://commons.apache.org/proper/commons-vfs/
that is Apache 2.0 licensed project.

javacup library is exluded from Knowage project.

opensaml should come from here:
https://mvnrepository.com/artifact/org.opensaml/opensaml
as you can see, license is Apache 2.0

jaxrpc is a Java specification, released under COMMON DEVELOPMENT AND DISTRIBUTION LICENSE (CDDL) Version 1.1 license:
https://mvnrepository.com/artifact/javax.xml/jaxrpc-api/1.1
https://github.com/javaee/jax-rpc-ri

flute is licensed under the W3C® SOFTWARE NOTICE AND LICENSE:
https://mvnrepository.com/artifact/org.milyn/flute/1.3
https://www.w3.org/Consortium/Legal/copyright-software-19980720

SDO API is licensed under the EDL 1.0 or EPL 1.0 licenses:
https://mvnrepository.com/artifact/org.eclipse.persistence/commonj.sdo

JA-SIG CAS Client for Java is licensed under the Apache 2.0 license:
https://mvnrepository.com/artifact/org.jasig.cas.client/cas-client-core

JA-SIG CAS Core is licensed under the Apache 2.0 license:
https://mvnrepository.com/artifact/org.jasig.cas/cas-server-core

**Comment by jason-fox** [comment]
@davide-zerbetto - thanks for checking. Looks like this is a false positive from the FOSSA Bot.
