### ISSUE TITLE
Knowage Server config error -client browser connect remote knowage server with url "localhost:8080"

### ISSUE THREAD

**Issue by frank-dkvan** [KnowageLabs/Knowage-Server#8]
when I try to create a cockpit in a client browser thru accessing to a remote knowage server. 
the function dialog can not be shown, a blank UI left.

I try to debug client Javascript thru browser debug console, finding the error info as follows:
" Failed to load resource: can not connect server。 http://localhost:8080/knowage/js/lib/angular/angular_1.4/angular.min.js"

**Comment by frank-dkvan** [comment]
when I try to change  "localhost:8080" to the true IP of that Knowage Server, the browser debug console hints the error information blow:"
Failed to load resource: the server responded with a status of 401 (Unauthorized)",
how to config them correctly?

**Comment by frank-dkvan** [comment]
it looks like an authorization problem after configuration in server.xml

**Comment by aportosa** [comment]
Dear frank-dkvan,
please report bugs by using our issue tracker: https://www.knowage-suite.com/jira
If you have any technical question, you can instead use out Q&A: https://www.knowage-suite.com/qa

Issue via Github will be disable soon.
