### ISSUE TITLE
locale language problem

### ISSUE THREAD

**Issue by hero5512** [KnowageLabs/Knowage-Server#86]
When I tried to sinicize this software, I encountered the following problem.

I login in the system using the admin user. 
![image](https://user-images.githubusercontent.com/10353921/59432570-3ae6aa00-8e1a-11e9-8e76-ba6eab693aa2.png)

I set the SPAGOBI.LANGUAGE_SUPPORTED.LANGUAGES to [it,IT],[en,US],[fr,FR],[es,ES],[cn,CN],[jp,JP].
![image](https://user-images.githubusercontent.com/10353921/59432634-5e115980-8e1a-11e9-9982-2356b34a5151.png)

However, when I select the Chinese, I encountered the following problem.
![image](https://user-images.githubusercontent.com/10353921/59432694-8bf69e00-8e1a-11e9-909c-f84fc5239dd6.png)
![image](https://user-images.githubusercontent.com/10353921/59432759-a597e580-8e1a-11e9-8b41-9a4d459c4989.png)

Who can help me? Thank you.

**Comment by n3ils** [comment]
Hi @hero5512,
 
The error is due to incorrect handling of translations for the Chinese language.
 
We have made the fix and will make the Chinese language available starting with Knowage 8.0 which will be released soon.
 
Greetings
Alberto
