### ISSUE TITLE
knowage 6.3 cockpit not working

### ISSUE THREAD

**Issue by sumankriti** [KnowageLabs/Knowage-Server#89]
**Describe the bug**
When I am clicking on cockpit then it showing me blank page. when I searched on net it saying change in **server.xml** host_url acc" server ip I tried that still same blank page.
2. When I checked in my developer tools saying that following :
 1. Loading failed for the <script> with source “http://192.168.0.3:8080/knowage/js/src/angular_1.4/tools/commons/services/knModule_fontIconsService.js”

2. Loading failed for the <script> with source “http://192.168.0.3:8080/knowage/js/src/angular_1.4/tools/commons/services/knModule.js”.

3.[$injector:nomod] Module 'knModule' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

**To Reproduce**
1. Go to 'http://192.168.56.101:8080/knowage'
2. Click on Document development.
3. click on + button.
4. click on Cockpit
5.Not showing anything.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Centos 7
 - Browser [Firefox,chrome]
 - Version [7]

**Additional context**
I am using knowage 6.3.3

**Comment by Teks71** [comment]
+1
`<script type="text/javascript" src="http://<domain>:8080/knowage/js/src/angular_1.4/tools/commons/services/knModule_fontIconsService.js"></script>`
and it's problem if you want use knowage with nginx
