### ISSUE TITLE
[Fatal Error] :2:1: Content is not allowed in prolog

### ISSUE THREAD

**Issue by csanouk** [KnowageLabs/Knowage-Server#926]
Hello,
I installed the latest version knowage 8.1.26 CE, I Tried to upload a csv file in mydatasets et I have the error [Fatal Error] :2:1: Content is not allowed in prolog.
It's a simple csv to test.
[MOCK_DATA.csv](https://github.com/user-attachments/files/17258435/MOCK_DATA.csv)
Thanks for your help
Regards
Sanouk

**Comment by Redjaw** [comment]
Hello, [this recent commit](https://github.com/KnowageLabs/Knowage-Server/commit/e8bf0bcd198af80f72d9dd3782d9d9c65a2b1e2c) should have fixed the issue.
Please wait for the next 8.1 update to see it solved.
Thank you and regards

**Comment by csanouk** [comment]
Hello, When the next update is expected ?
Thank you
Regards

**Comment by Redjaw** [comment]
Hello, I think at the end of this week
Regards

**Comment by csanouk** [comment]
Ok
Thank you
