### ISSUE TITLE
EMail input field does not allow sub domains in mail addresses.

### ISSUE THREAD

**Issue by xylo** [KnowageLabs/Knowage-Server#95]
**Describe the bug**
I logged in and went to the "My Account" page to change my email address.  Unfortunately the email input field does not allow email addresses with sub domains, e.g. user@sub.example.com.

**To Reproduce**
1. Log in and go to "My Account"
2. Enter "user@sub.example.com" in the email field.
4. See that the mail address is underlined red.

**Expected behavior**
"user@sub.example.com" and other valid email addresses should be accepted.
An example for a good regular expression for email validation seems to be on https://www.regextester.com/19.

**Screenshots**
![image](https://user-images.githubusercontent.com/577869/62463820-4e175580-b78b-11e9-9232-9c893da7e98d.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Chrome
 - Version: 6.4.3

**Comment by n3ils** [comment]
Hi @xylo,

Thank you for the report. This issue will be solved in future versions of Knowage. If you need specific resolution times, please contact us for a professional service via [https://www.knowage-suite.com/site/about-us/knowage-contacts/#1575990894250-05851a50- 1b43](url).

Thank you

Alberto
