### ISSUE TITLE
Knowage report with BIRT

### ISSUE THREAD

**Issue by harikrishnan891** [KnowageLabs/Knowage-Server#98]
While navigate through Cross navigation with Knowage shows the following error 
"Uncaught TypeError: Cannot read property '$parent' of undefined
    at execExternalCrossNavigation (documentExecution.js:727)
    at <anonymous>:1:8
execExternalCrossNavigation @ documentExecution.js:727
(anonymous) @ VM11011:1"
While in the knowage side its working good and also its drill through next report but in client side it shows the error

**Comment by jomonthomaslobo** [comment]
Check the params

**Comment by mcortella** [comment]
> While navigate through Cross navigation with Knowage shows the following error
> "Uncaught TypeError: Cannot read property '$parent' of undefined
> at execExternalCrossNavigation (documentExecution.js:727)
> at :1:8
> execExternalCrossNavigation @ documentExecution.js:727
> (anonymous) @ VM11011:1"
> While in the knowage side its working good and also its drill through next report but in client side it shows the error

What do you mean by client? The Birt designer?
The cross navigation is meant to be used only inside Knowage, is not part of the Birt standard functions.

**Comment by harikite** [comment]
> > While navigate through Cross navigation with Knowage shows the following error
> > "Uncaught TypeError: Cannot read property '$parent' of undefined
> > at execExternalCrossNavigation (documentExecution.js:727)
> > at :1:8
> > execExternalCrossNavigation @ documentExecution.js:727
> > (anonymous) @ VM11011:1"
> > While in the knowage side its working good and also its drill through next report but in client side it shows the error
> 
> What do you mean by client? The Birt designer?
> The cross navigation is meant to be used only inside Knowage, is not part of the Birt standard functions.
Hi Client means in Angular 6  ,  Actually i design the report in BIRT and deploy it in knowage , its working also we can drill through to next report but in my Client side(Angular6) it show the above error while navigate to next report
